apiVersion: v1                 # Core Kubernetes API version for Service resource
kind: Service                  # Defines a Service, which routes network traffic to Pods

metadata:
  name: mongo-headless         # Name of this Service; used to reference it within the cluster

spec:
  clusterIP: None              # Headless service: no cluster IP assigned
                               # This means DNS will return the pod IPs directly, enabling direct Pod-to-Pod communication

  selector:
    app: mongo                 # Selects Pods with label 'app: mongo' to associate with this Service

  ports:
    - port: 27017              # Port exposed by the Service (inside cluster)
      targetPort: 27017        # Port on the target Pods (MongoDB’s default port)
