apiVersion: v1                   # Core Kubernetes API version for PVC resources
kind: PersistentVolumeClaim      # Declares a request for storage from a PersistentVolume

metadata:
  name: mongo-pvc                # Name of this PersistentVolumeClaim

spec:
  accessModes:
    - ReadWriteOnce             # Specifies the access mode:
                                # ReadWriteOnce means the volume can be mounted as read-write by a single node

  resources:
    requests:
      storage: 1Gi              # Requesting 1 Gigabyte of storage space
