FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY *.sln ./
COPY CustomerApi/*.csproj ./CustomerApi/
RUN dotnet restore

COPY CustomerApi/. ./CustomerApi/
WORKDIR /app/CustomerApi
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/CustomerApi/out .

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT ["dotnet", "CustomerApi.dll"]
