version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: CustomerApi/Dockerfile
    image: customer-api:latest
    ports:
      - "8080:80"
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=customerdb
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
    volumes:
      - app_data:/app/data
    networks:
      - backend_net

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: customerdb
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "true"]
    networks:
      - backend_net

volumes:
  mongo_data:
  app_data:

networks:
  backend_net:
    driver: bridge
